const assert = require('node:assert/strict');
const { test } = require('node:test');
const createDdlProvider = require('../forward_engineering/ddlProvider/ddlProvider');

const ddlProvider = createDdlProvider(null, null, null);

void test('places NOT NULL before the ROWID generated clause', () => {
	const columnDefinition = ddlProvider.convertColumnDefinition({
		name: 'row_id',
		type: 'ROWID',
		primaryKey: false,
		unique: false,
		nullable: false,
		generated: 'ALWAYS',
		isActivated: true,
	});

	assert.equal(columnDefinition, '"row_id" ROWID NOT NULL GENERATED ALWAYS');
});

void test('places NOT NULL before a column default', () => {
	const columnDefinition = ddlProvider.convertColumnDefinition({
		name: 'count',
		type: 'INTEGER',
		primaryKey: false,
		unique: false,
		nullable: false,
		default: 0,
		isActivated: true,
	});

	assert.equal(columnDefinition, '"count" INTEGER NOT NULL WITH DEFAULT 0');
});

void test('keeps inline key constraints after identity generation', () => {
	const columnDefinition = ddlProvider.convertColumnDefinition({
		name: 'id',
		entityName: 'sample',
		type: 'INTEGER',
		primaryKey: true,
		unique: false,
		nullable: false,
		isActivated: true,
		identity: {
			generated: 'ALWAYS',
			start: 1,
		},
	});

	assert.equal(
		columnDefinition,
		'"id" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1) CONSTRAINT "sample_pk" PRIMARY KEY',
	);
});

void test('omits the empty parentheses when identity has no options', () => {
	const columnDefinition = ddlProvider.convertColumnDefinition({
		name: 'id',
		type: 'BIGINT',
		primaryKey: false,
		unique: false,
		nullable: false,
		isActivated: true,
		identity: {
			generated: 'ALWAYS',
		},
	});

	assert.equal(columnDefinition, '"id" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY');
});

void test('emits the ROW CHANGE TIMESTAMP generated clause', () => {
	const columnDefinition = ddlProvider.convertColumnDefinition({
		name: 'last_mod',
		type: 'TIMESTAMP',
		primaryKey: false,
		unique: false,
		nullable: false,
		isActivated: true,
		generatedColumn: true,
		generatedColumnType: 'ROW CHANGE TIMESTAMP',
	});

	assert.equal(
		columnDefinition,
		'"last_mod" TIMESTAMP NOT NULL GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP',
	);
});

void test('emits the ROW BEGIN generated clause', () => {
	const columnDefinition = ddlProvider.convertColumnDefinition({
		name: 'sys_start',
		type: 'TIMESTAMP',
		primaryKey: false,
		unique: false,
		nullable: false,
		isActivated: true,
		generatedColumn: true,
		generatedColumnType: 'ROW BEGIN',
	});

	assert.equal(columnDefinition, '"sys_start" TIMESTAMP NOT NULL GENERATED ALWAYS AS ROW BEGIN');
});

void test('emits GENERATED BY DEFAULT for the ROW CHANGE TIMESTAMP generated clause', () => {
	const columnDefinition = ddlProvider.convertColumnDefinition({
		name: 'last_mod',
		type: 'TIMESTAMP',
		primaryKey: false,
		unique: false,
		nullable: false,
		isActivated: true,
		generatedColumn: true,
		generatedColumnType: 'ROW CHANGE TIMESTAMP',
		generatedColumnGenerated: 'BY DEFAULT',
	});

	assert.equal(
		columnDefinition,
		'"last_mod" TIMESTAMP NOT NULL GENERATED BY DEFAULT FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP',
	);
});

void test('emits NO MAXVALUE / NO MINVALUE instead of numeric bounds', () => {
	const columnDefinition = ddlProvider.convertColumnDefinition({
		name: 'id',
		type: 'BIGINT',
		primaryKey: false,
		unique: false,
		nullable: false,
		isActivated: true,
		identity: { generated: 'ALWAYS', noMaxValue: true, noMinValue: true },
	});

	assert.equal(columnDefinition, '"id" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (NO MINVALUE, NO MAXVALUE)');
});

void test('emits IMPLICITLY HIDDEN after a ROWID generated clause', () => {
	const columnDefinition = ddlProvider.convertColumnDefinition({
		name: 'row_id',
		type: 'ROWID',
		primaryKey: false,
		unique: false,
		nullable: false,
		generated: 'ALWAYS',
		implicitlyHidden: true,
		isActivated: true,
	});

	assert.equal(columnDefinition, '"row_id" ROWID NOT NULL GENERATED ALWAYS IMPLICITLY HIDDEN');
});

void test('emits IMPLICITLY HIDDEN after an identity clause', () => {
	const columnDefinition = ddlProvider.convertColumnDefinition({
		name: 'id',
		type: 'BIGINT',
		primaryKey: false,
		unique: false,
		nullable: false,
		isActivated: true,
		identity: { generated: 'ALWAYS' },
		implicitlyHidden: true,
	});

	assert.equal(columnDefinition, '"id" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY IMPLICITLY HIDDEN');
});

void test('does not emit IMPLICITLY HIDDEN for a plain expression-generated column', () => {
	const columnDefinition = ddlProvider.convertColumnDefinition({
		name: 'full_name',
		type: 'VARCHAR',
		length: 100,
		primaryKey: false,
		unique: false,
		nullable: false,
		isActivated: true,
		generatedColumn: true,
		columnGenerationExpression: "first_name || ' ' || last_name",
		implicitlyHidden: true,
	});

	assert.ok(!columnDefinition.includes('IMPLICITLY HIDDEN'));
});
